### PR TITLE
Update mcr.cpp

### PR DESCRIPTION
**Pull request by fanjiangchenghe**
Add an optional extended description

### CODE REVIEW

**Review by fanjiangchenghe — COMMENTED** [review]
don't need

**Review by Stardust-lf — COMMENTED** [review]
judgement for i==3 should be moved up

**Review by mortlight — COMMENTED** [review]
The inspection on the validity of variable i and j shoud be checked.

**Comment by Xuyaolin921** [comment]
“X””O”should be changed to the Enumeration of string structures

**Comment by liweixin** [comment]
amazing

**Pull request merged**
